### PR TITLE
Release branch.go1.10

### PR DESCRIPTION
**Pull request by minddrive**
Merge latest http2 from Go

### CODE REVIEW

**Comment by abhinavdangeti** [comment]
Looks good to me!

**Comment by steveyen** [comment]
looks ok to me, too.  lots of changes -- this mirror was due for an update

but, of note, there might be some potential devil-in-the-details interactions here between golang.org/x/net and golang.org/net -- have already pinged @abhinavdangeti about those

**Comment by minddrive** [comment]
@steveyen Do you want me to hold off on merging, then?

**Comment by steveyen** [comment]
> Do you want me to hold off on merging, then?

@minddrive - nope, this is looks long due for a refreshed merge so good to go

**Comment by minddrive** [comment]
Done!

**Pull request merged**
